### ISSUE TITLE
Boost exception thrown in nox causing very low throughput

### ISSUE THREAD

**Issue by monasinha194** [noxrepo/nox#10]
228026|openflow-datapath|DBG:received ofp_packet_in
228027|openflow-datapath|DBG:sending ofp_flow_mod
228028|event-dispatcher|ERR:Event ofp_packet_in processing leaked an exception: boost::asio::streambuf too long
228029|event-dispatcher|ERR:Extra information:
Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_implboost::exception_detail::error_info_injector<std::length_error >
std::exception::what: boost::asio::streambuf too long
228030|openflow-datapath|DBG:received ofp_packet_in
228031|openflow-datapath|DBG:sending ofp_flow_mod
228032|event-dispatcher|ERR:Event ofp_packet_in processing leaked an exception: boost::asio::streambuf too long
228033|event-dispatcher|ERR:Extra information:
Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_implboost::exception_detail::error_info_injector<std::length_error >
std::exception::what: boost::asio::streambuf too long
228034|openflow-datapath|DBG:received ofp_packet_in
228035|openflow-datapath|DBG:sending ofp_flow_mod
228036|event-dispatcher|ERR:Event ofp_packet_in processing leaked an exception: boost::asio::streambuf too long
228037|event-dispatcher|ERR:Extra information:
Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_implboost::exception_detail::error_info_injector<std::length_error >

Output:

17:39:15.109 1   switches: flows/sec:  3995   total = 2.240731 per ms 
17:39:16.959 1   switches: flows/sec:  1843   total = 1.053301 per ms 
17:39:18.062 1   switches: flows/sec:  1843   total = 1.838457 per ms 
17:39:19.783 1   switches: flows/sec:  1851   total = 1.141512 per ms 
17:39:21.668 1   switches: flows/sec:  1844   total = 1.033481 per ms 
17:39:22.786 1   switches: flows/sec:  1843   total = 1.810375 per ms 
17:39:24.701 1   switches: flows/sec:  2458   total = 1.354281 per ms 
17:39:25.802 1   switches: flows/sec:  1844   total = 1.843766 per ms 
17:39:27.700 1   switches: flows/sec:  2458   total = 1.366717 per ms 
17:39:28.819 1   switches: flows/sec:  0   total = 0.000000 per ms 
RESULT: 1 switches 9 tests min/max/avg/stdev = 0.00/1843.77/1271.32/547.02 responses/s

**Comment by tootoonchian** [comment]
Is the setting different than what you sent to the mailing list? If not, I'll reopen the issue.

**Comment by monasinha194** [comment]
Hi amin, the setting was same.Also, I am using an x86_64 architecture, dual core processor.I tried with single thread too results were not appropriate.

**Comment by tootoonchian** [comment]
With a dual-core processor, go with 1 or 2 threads.

Amin

**Comment by monasinha194** [comment]
Yes , I did that too. But all in vain :(

**Comment by tootoonchian** [comment]
Can you show the commands you used in your last run?

**Comment by monasinha194** [comment]
sudo apt-get update

wget -c 'http://sourceforge.net/projects/boost/files/boost/1.50.0/boost_1_50_0.tar.bz2/download'

tar xf download

cd boost_1_50_0

./bootstrap.sh

./b2 install

./configure --prefix=/usr --with-boost-libdir=/usr/local/lib --enable-ndebug

make clean

 make -j

Run nox through 

taskset -c 0 ./nox_core -i ptcp:0.0.0.0:6633  -v switch -t 1

Cbench installtion:

Downloaded cbench

./configure
make 
make install

Run through :

cbench -c localhost -M 10000 -m 1000 -s 16 -l 10 -t

**Comment by monasinha194** [comment]
sudo apt-get update

wget -c '
http://sourceforge.net/projects/boost/files/boost/1.50.0/boost_1_50_0.tar.bz2/download
'

tar xf download

cd boost_1_50_0

./bootstrap.sh

./b2 install

./configure --prefix=/usr --with-boost-libdir=/usr/local/lib --enable-ndebug

make clean

make -j

Run nox through

taskset -c 0 ./nox_core -i ptcp:0.0.0.0:6633 -v switch -t 1

Cbench installtion:

Downloaded cbench

./configure
make
make install

Run through :

cbench -c localhost -M 10000 -m 1000 -s 16 -l 10 -t
