### ISSUE TITLE
ethernetaddr.cc was put in the worng place

### ISSUE THREAD

**Issue by Jinhui-Wu** [noxrepo/nox#12]
Maybe, ethernetaddr.cc should be put  src/lib/netinet++ instead of src/include/netinet++.  
What's more, src/lib/netinet++/Makefile.am should include ethernetaddr.cc.
Thank you.

**Comment by vitalivanov** [comment]
File ethernetaddr.cc is not compiled in at all for now.
But ethernetaddr.hh is using functions that are part of cc file.
As a result if you want to link with 'ethernetaddr(const char*);' for example, then linker would fail.

Creating a pull request to fix it by moving functions from cc to hh, making them inline similarly to other files/functions in netinet++ lib. Plus small cleanups:

https://github.com/noxrepo/nox/pull/13
