### ISSUE TITLE
"unreliable" cmd line option is not implemented. nox_main.cc:293:10: warning: variable ‘reliable’ set but not used.

### ISSUE THREAD

**Issue by vitalivanov** [noxrepo/nox#15]
I can see the following warning when building nox:

../../src/nox_main.cc: In function ‘int main(int, char**)’:
../../src/nox_main.cc:293:10: warning: variable ‘reliable’ set but not used [-Wunused-but-set-variable]

This flag is controlled by 'unreliable' cmd line option. For now it's not implemented.

I can compile off 'unreliable' option by wrapping it under some macro or if there is infrastructure for this I can add functionality to control 'reconnect to interface on error'.

Need some hints.

**Comment by tootoonchian** [comment]
The underlying functionality was removed from NOX as I didn't implement any other form of transport other than TCP in Verity, but didn't removed the command line option (hoping that we may introduce other transports).

**Comment by vitalivanov** [comment]
My intention was to clean this warning.
If it can be used in future maybe we can disable it for now under precompile macro?

**Comment by tootoonchian** [comment]
That sounds good do me if you want to submit a patch.
