### ISSUE TITLE
Missing byteswap.h on Mac OSX

### ISSUE THREAD

**Issue by fooling** [noxrepo/nox#18]
I got this message when compiling nox source

> In file included from network_iarchive.cc:1:
> In file included from ../../src/include/network_iarchive.hh:17:
> ../../src/include/network_archive.hh:4:10: fatal error: 'byteswap.h' file not found
> # include <byteswap.h>

Probably because Mac OS X has no byteswap.h C header file

**Comment by tootoonchian** [comment]
Even though NOX is pretty much platform independent (thanks to Boost), it doesn't compile on Mac yet. The issues are pretty easy to fix but no one in our team had the time to do it. If you are willing to investigate it, I'd happy to push the changes.
