### ISSUE TITLE
bugs in ofp_match::from_packet

### ISSUE THREAD

**Issue by sharkdtu** [noxrepo/nox#22]
in the function ofp_match::from_packet():
...............
...............
else if (nw_proto() == ip_::proto::ICMP)
{
      const icmp_header\* icmp = cast_check<const icmp_header>(packet);
      if (!icmp)
             return;
      packet = packet + sizeof(icmp_header);
      tp_src(ntohs(icmp->icmp_type));
      tp_dst(ntohs(icmp->icmp_code));
 }
..............
the type of "icmp->icmp_type" and "icmp->icmp_code" are uint8_t, they shoud not be converted to host byte order by calling "ntohs". simply fix it like that:
tp_src(icmp->icmp_type);
tp_dst(icmp->icmp_code);

**Comment by tootoonchian** [comment]
Fixed. Thanks!
