### ISSUE TITLE
dl_src and dl_dst not set properly.

### ISSUE THREAD

**Issue by vjeko** [noxrepo/nox#3]
Currently, ofp_match::from_packet() does not set Ethernet addresses when Ethernet Type is IPv6.

**Comment by tootoonchian** [comment]
Thanks Vjeko. I will fix it asap.

**Comment by tootoonchian** [comment]
There were a couple of bugs in ofp_match::from_packet() that I tried to address. Could you try the following patch to see if it fixes the issue you had and if it doesn't break anything else?

https://gist.github.com/3167678

**Comment by vjeko** [comment]
Thanks a bunch It fixed a couple of other bugs as well.

Also, just a minor comment -- dl_type is not being set for protocols that do not match your control flow.

**Comment by tootoonchian** [comment]
Thanks Vjeko! After your comment I realized I used dl_type() before assignment and fixed it. But other than that I don't see when dl_type is not set. It is set for Ethernet II and LLC/SNAP frame types. Is there any other case we are missing?
