### ISSUE TITLE
Run time Error in MPLS-TE Demo

### ISSUE THREAD

**Issue by ash27win** [noxrepo/nox#30]
I'm getting following Runtime Error followed the steps in the link 
http://archive.openflow.org/wk/index.php/MPLS-TE_Demo.   Compilation was successful.Any clues??

"jslib/buildUtil.js#611(eval)", line 24: uncaught JavaScript runtime exception:
SyntaxError: missing } after property list
copyrightFile: "../../nox/uiapps/coreui/coreui/nox-js-copyright.txt"

Thanks 
Ashwin

**Comment by tootoonchian** [comment]
Unfortunately those legacy demos are no longer supported and we cannot provide support for them. 

Amin
