### ISSUE TITLE
installing flow entries for the group table. 

### ISSUE THREAD

**Issue by pankajskku** [noxrepo/nox#33]
I am using fast-failover group type in my project using NOX and mininet. But i am having some issues with the NOX code for installing flow entries for the group table. 
I am trying install a flow from port 1 to port 2 of a switch but if port 2 fails then it should transfer the traffic to the port 3 without controller intervention. 

f1->Add_Field("in_port", 1); 
f1->Add_Field("eth_type", ntohs(ethernet::IP) ); 
f1->Add_Field("ipv4_src", "10.0.0.1"); 
f1->Add_Field("ipv4_dst", "10.0.0.1"); 

if(htonl(dpj.dpid.as_host()) == htonl(0x1) ) 
{ 
cout <<"installing flow for switch 1" << endl; 

Actions *acts1 = new Actions(); 
acts1->CreateOutput(2); 

Instruction *inst = new Instruction(); 
inst->CreateApply(acts1); 

struct ofp_bucket *bucketff = (struct ofl_bucket *)malloc(sizeof(struct ofl_bucket));; 
bucketff->watch_group = 1; 
bucketff->watch_port = 2; 
bucketff->weight = 1; 

FlowMod _mod = new FlowMod(0x00ULL,0x00ULL, 0,OFPGC_ADD, 1, OFP_FLOW_PERMANENT, 
OFP_DEFAULT_PRIORITY, 0 /_in.buffer_id*/, OFPP_ANY, OFPG_ANY, ofd_flow_mod_flags()); 

mod->AddMatch(&f1->match); 
mod->AddInstructions(inst); 
} 
I would really appreciate if you give any input.

**Comment by MurphyMc** [comment]
I think you're using the CPqD fork of NOX, which isn't maintained here.  Sorry!  You'll have to look to them for answers.

**Comment by pankajskku** [comment]
Thanks for the quick reply. :) Yes i am using CPqD fork of NOX.

**Comment by MurphyMc** [comment]
No problem.  Specifically, my best guess is the tracker at...
https://github.com/CPqD/nox13oflib
