### ISSUE TITLE
Problems when trying to create a new component on new NOX

### ISSUE THREAD

**Issue by Jordan-Queiroz** [noxrepo/nox#34]
Hi, folks
I'm trying to create a new component on new nox, but I'm having some problems, which I've tried to solve with this tutorial: http://www.noxrepo.org/_/nox-classic-doxygen/Howto.html
The problems I'm facing are: 1) add the meta.json and the Makefile.am (because I don't know how to write these files, so I simply copied these files from switch's module directory to my new module's directory, but I don't know if did it in the right way); 2) When I try to compile the nox using these commands (and consequently make my new component be compiled too): ./boot.sh; configure and make, the following mensages appears:

mininet@mininet-vm:~/nox/build$ sudo make
 (note: before this command, I had executed the ./boot.sh and ../configure (this last one, from the inside of build directory))

make  all-recursive
make[1]: Entering directory `/home/mininet/nox/build'

Making all in src
make[2]: Entering directory `/home/mininet/nox/build/src'
make  all-recursive
make[3]: Entering directory`/home/mininet/nox/build/src'
Making all in include
make[4]: Entering directory `/home/mininet/nox/build/src/include'
make[4]: Nothing to be done for`all'.
make[4]: Leaving directory `/home/mininet/nox/build/src/include'
Making all in lib
make[4]: Entering directory`/home/mininet/nox/build/src/lib'
make  all-am
make[5]: Entering directory `/home/mininet/nox/build/src/lib'
make[5]: Nothing to be done for`all-am'.
make[5]: Leaving directory `/home/mininet/nox/build/src/lib'
make[4]: Leaving directory`/home/mininet/nox/build/src/lib'
Making all in utilities
make[4]: Entering directory `/home/mininet/nox/build/src/utilities'
make  all-am
make[5]: Entering directory`/home/mininet/nox/build/src/utilities'
make[5]: Nothing to be done for `all-am'.
make[5]: Leaving directory`/home/mininet/nox/build/src/utilities'
make[4]: Leaving directory `/home/mininet/nox/build/src/utilities'
Making all in etc
make[4]: Entering directory`/home/mininet/nox/build/src/etc'
make  all-am
make[5]: Entering directory `/home/mininet/nox/build/src/etc'
make[5]: Leaving directory`/home/mininet/nox/build/src/etc'
make[4]: Leaving directory `/home/mininet/nox/build/src/etc'
Making all in coreapps
make[4]: Entering directory`/home/mininet/nox/build/src/coreapps'
make  all-recursive
make[5]: Entering directory `/home/mininet/nox/build/src/coreapps'
Making all in openflow
make[6]: Entering directory`/home/mininet/nox/build/src/coreapps/openflow'
make  all-am
make[7]: Entering directory `/home/mininet/nox/build/src/coreapps/openflow'
make[7]: Leaving directory`/home/mininet/nox/build/src/coreapps/openflow'
make[6]: Leaving directory `/home/mininet/nox/build/src/coreapps/openflow'
Making all in switch
make[6]: Entering directory`/home/mininet/nox/build/src/coreapps/switch'
make  all-am
make[7]: Entering directory `/home/mininet/nox/build/src/coreapps/switch'
make[7]: Leaving directory`/home/mininet/nox/build/src/coreapps/switch'
make[6]: Leaving directory `/home/mininet/nox/build/src/coreapps/switch'
Making all in firewall
make[6]: Entering directory`/home/mininet/nox/build/src/coreapps/firewall'
make  all-am
make[7]: Entering directory `/home/mininet/nox/build/src/coreapps/firewall'
make[7]: *** No rule to make target`switch.cc', needed by `switch_la-switch.lo'.  Stop.
make[7]: Leaving directory`/home/mininet/nox/build/src/coreapps/firewall'
make[6]: **\* [all] Error 2
make[6]: Leaving directory `/home/mininet/nox/build/src/coreapps/firewall'
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory`/home/mininet/nox/build/src/coreapps'
make[4]: **\* [all] Error 2
make[4]: Leaving directory `/home/mininet/nox/build/src/coreapps'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory`/home/mininet/nox/build/src'
make[2]: **\* [all] Error 2
make[2]: Leaving directory `/home/mininet/nox/build/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/mininet/nox/build'
make: **\* [all] Error 2
mininet@mininet-vm:~/nox/build$ 

I'm struggling with these problems for two days and I don't know how to solve them. I also took a look on nox repo tutorial on github (https://github.com/noxrepo/nox-classic/wiki/Developing-in-NOX) and the doxygen (http://www.noxrepo.org/_/nox-doxygen/), but I didn't find anything that could help me.

![problemwithnewcomponent](https://cloud.githubusercontent.com/assets/4997632/4372485/812e6be2-4324-11e4-8ff2-d9e117e12e79.png)

Can anyone help me??
Thanks in advance.

**Comment by tootoonchian** [comment]
It seems that you haven't updated the content of the files you copied over. Just replace the occurrences of switch with the proper file names.

**Comment by Jordan-Queiroz** [comment]
You are right, I haven't updated the files...
But now I have updated them and everything is working. Thank you.
