### ISSUE TITLE
How to set priority on flow rules?

### ISSUE THREAD

**Issue by Jordan-Queiroz** [noxrepo/nox#35]
Hi, folks.
I'm trying to set up a priority level on a flow rule, but the solution I have tried didn't work. There is a piece of code where it is possible to change the priority level (at least I think):

![priority](https://cloud.githubusercontent.com/assets/4997632/4483615/2ca12142-49b3-11e4-9725-a89a1580eda5.png)

I'm trying to edit this field (the blue-marked one) because according with I've searched, a priority level of a flow rule affects the order where the match is done in the flowtable.
The problem is whenever I try to change the priority's level (by editing this blue-marked-field), nothing happens (it is possible to realize it using dpctl). According with NOX's documentation in doxygen (http://www.noxrepo.org/_/nox-doxygen/openflow-defs-1_80_8hh_source.html) there is only DEFAULT_PRIORITY, which its value is set in hexadecimal. So I have tried to set other values (lower values) in hexadecimal (LOW_PRIORITY's value is 0x7000 and the DEFAULT_PRIORITY's value is 0x8000), but whenever I check the priority's level in dpctl, it always shows me priority's level in 65535

Does anyone have a solution to solve it??
Thanks in advance.

**Comment by MurphyMc** [comment]
Exact matches always have high priority (at least in OpenFlow 1.0).

**Comment by Jordan-Queiroz** [comment]
In this case, how do I do to make a match be inexact?
I really need to modify the flow rule's priority level. Is there any way to do it??
