### ISSUE TITLE
complete version of nox

### ISSUE THREAD

**Issue by Maryam-Maya-Karimi** [noxrepo/nox#37]
Hi
I read the about nox in wiki page and it seems that the version of nox in this site is not complete for example it does not include pyswitch component or discovery or messenger , ...
is there any complete version of nox for download? would you show me a link for that, please?
thank you in advance

**Comment by tootoonchian** [comment]
NOX no longer includes sample applications but POX does if that's what you're looking for. See https://github.com/noxrepo/pox.

**Comment by matrix69** [comment]
Thank you very much. As I read in papers, almost all of software defined wireless networks are using NOX controller. do you know any reference about using POX in wireless networks?
