### ISSUE TITLE
Unable to install on Ubuntu 20.04

### ISSUE THREAD

**Issue by fahadnaeem** [noxrepo/nox#39]
I'm unable to install nox controller on Ubuntu 20.04
`./boot.sh` runs fine but when I try to run `../configure` it gives me errors like
`configure: error: cannot find install-sh, install.sh, or shtool in ".." "../.." "../../.."`
I've updated and upgraded Ubuntu but nothing works. Kindly help me out.

**Comment by MurphyMc** [comment]
I haven't built NOX for a while; you may indeed have a number of problems building it on 20.04 (especially if you are building classic NOX and want Python bindings).  But the first thing I'd try is the following:
```
apt install doxygen build-essential autoconf automake make g++ libtool python libssl-dev libboost-dev libtbb-dev
```

If that doesn't help, maybe I'd try throwing in `apt install shtool` also.

**Comment by fahadnaeem** [comment]
> I haven't built NOX for a while; you may indeed have a number of problems building it on 20.04 (especially if you are building classic NOX and want Python bindings). But the first thing I'd try is the following:
> 
> ```
> apt install doxygen build-essential autoconf automake make g++ libtool python libssl-dev libboost-dev libtbb-dev
> ```
> 
> If that doesn't help, maybe I'd try throwing in `apt install shtool` also.

**Comment by fahadnaeem** [comment]
Thank you so much for your reply. What would be the latest Ubuntu version I can try installing and running it on?

**Comment by fahadnaeem** [comment]
> apt install shtool

I tried everything but still getting the same thing on Ubuntu 20.04
It's not even working on Ubuntu 14.04 and giving me error of no makefile found.

**Comment by MurphyMc** [comment]
On 14.04, you ran the boot script and then configure seemed to run okay, but then make gives you an error about no makefile?

**Comment by fahadnaeem** [comment]
> On 14.04, you ran the boot script and then configure seemed to run okay, but then make gives you an error about no makefile?

Yes, Mr. Murphy. That's exactly what happened.

**Comment by MurphyMc** [comment]
I think configure actually probably ended with an error.

The m4 files in the repo are very old.  The first thing I'd do is update them; especially the boost ones.  Get the autoconf archive (https://www.gnu.org/software/autoconf-archive/Downloads.html), and replace all the ax_boost files in m4/ with the ones from the archive.  Then try ./boot.sh and configure again.
