### ISSUE TITLE
Controller Connected but no ping response

### ISSUE THREAD

**Issue by fahadnaeem** [noxrepo/nox#40]
I have executed controller command using `./nox_core -v -i ptcp:6633` but when I run any topology using mininet, I'm unable to get ping response, though controller is connected and I get following response 

`00606|connection_manager|WARN:connected: 192.168.184.135:6633<->192.168.184.128:39770`
`00607|connection|DBG:flushed (tx: 0, rx: 0)`

Please I net help regarding this issue.

**Comment by MurphyMc** [comment]
NOX doesn't "do" anything by itself.  You'll need to run a component that actually takes care of getting traffic from one place to another.  Really, NOX is a platform for writing such components yourself, though it does come with some handy ones to get you started, e.g., the "switch" component.  To run that, throw a `switch` onto the end of your commandline.

**Comment by fahadnaeem** [comment]
> NOX doesn't "do" anything by itself. You'll need to run a component that actually takes care of getting traffic from one place to another. Really, NOX is a platform for writing such components yourself, though it does come with some handy ones to get you started, e.g., the "switch" component. To run that, throw a `switch` onto the end of your commandline.

Thank you for your response and help. NOX-Classic have many applications like routing, spanning tree protocol. How do we import them for NOX-MT ?

**Comment by MurphyMc** [comment]
There's no simple importing.  Enough has changed that it may take a fair bit of rewriting the old ones.
