### ISSUE TITLE
error: no matching function for call to ‘boost::property_tree::basic_ptree

### ISSUE THREAD

**Issue by marvelliu** [noxrepo/nox#8]
hi:

I am trying to build nox on ubuntu 12.10, but the "make -j" process fails and the output is:

../../src/builtin/component.cc:414:1:   required from here
/usr/include/boost/property_tree/detail/json_parser_read.hpp:105:17: error: no matching function for call to ‘boost::property_tree::basic_ptreestd::basic_string<char, std::basic_string<char> >::push_back(std::pairstd::basic_string<char, std::basic_string<char> >)’
/usr/include/boost/property_tree/detail/json_parser_read.hpp:105:17: note: candidate is:
In file included from /usr/include/boost/property_tree/ptree.hpp:516:0,
                 from ../../src/include/component.hh:35,
                 from ../../src/builtin/component.cc:18:
/usr/include/boost/property_tree/detail/ptree_implementation.hpp:362:9: note: boost::property_tree::basic_ptree<Key, Data, KeyCompare>::iterator boost::property_tree::basic_ptree<Key, Data, KeyCompare>::push_back(const value_type&) [with Key = std::basic_string<char>; Data = std::basic_string<char>; KeyCompare = std::lessstd::basic_string<char >; boost::property_tree::basic_ptree<Key, Data, KeyCompare>::value_type = std::pair<const std::basic_string<char>, boost::property_tree::basic_ptreestd::basic_string<char, std::basic_string<char> > >]
/usr/include/boost/property_tree/detail/ptree_implementation.hpp:362:9: note:   no known conversion for argument 1 from ‘std::pairstd::basic_string<char, std::basic_string<char> >’ to ‘const value_type& {aka const std::pair<const std::basic_string<char>, boost::property_tree::basic_ptreestd::basic_string<char, std::basic_string<char> > >&}’
make[4]: **\* [nox_core-component.o] Error 1
make[4]: Leaving directory `/home/nsfocus/nox/build/src'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory`/home/nsfocus/nox/build/src'
make[2]: **\* [all] Error 2
make[2]: Leaving directory `/home/nsfocus/nox/build/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/nsfocus/nox/build'
make: **\* [all] Error 2

I am not familiar with C++, so can someone fix this issue, please.

P.S. I find that the project is not updated for months, is this the newest version of Nox?

**Comment by tootoonchian** [comment]
This is not a NOX bug, but an issue in Boost due a change of behavior in compiler. Just upgrade to a newer boost library. On Ubuntu 12.10 Boost 1.50 has this issue fixed.

If you prefer to manually fix it see https://svn.boost.org/trac/boost/ticket/6785.
